[project]
name = "runnerforge"
version = "0.1.0"
description = "Self-hosted runners on GCP for Github Actions"
readme = "README.md"
authors = [{ name = "Ruman Kazi", email = "kaziruman@gmail.com" }]
requires-python = ">=3.14"
dependencies = ["fastapi[standard]>=0.136.3"]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "ruff>=0.15.14",
]
