name: Actionlint

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'
  push:
    branches: [main]
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - uses: reviewdog/action-actionlint@49cb3ce06e5d81452e14b38ad34e4b12a8acfe2b # v1.73.3
        with:
          reporter: github-pr-check
          fail_level: error
