name: Drift Detection

on:
  schedule:
    - cron: "17 8 * * *"   # daily 08:17 UTC
  workflow_dispatch:

permissions: {}

concurrency:
  group: terraform-drift
  cancel-in-progress: true   # newer scheduled run replaces stale one

env:
  WIF_PROVIDER: projects/8547588670/locations/global/workloadIdentityPools/github/providers/github
  CI_TERRAFORM_PLAN_SA: ci-terraform-plan@runnerforge.iam.gserviceaccount.com

jobs:
  pick-out:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    outputs:
      issues: ${{ steps.pick-out.outputs.issues }}
      has_issues: ${{ steps.pick-out.outputs.has_issues }}
    permissions:
      contents: read
      issues: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: suzuki-shunsuke/tfaction@6ad59de70ee7e9c0a11c665c4439b5c148c74328 # v2.0.1
        id: pick-out
        with:
          action: pick-out-drift-issues

  detect:
    timeout-minutes: 20
    name: "detect (${{ matrix.issue.target }})"
    runs-on: ${{ matrix.issue.runs_on }}
    needs: pick-out
    permissions:
      issues: write
      contents: read
    if: fromJSON(needs.pick-out.outputs.has_issues)
    strategy:
      fail-fast: false
      matrix:
        issue: ${{fromJSON(needs.pick-out.outputs.issues)}}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: suzuki-shunsuke/tfaction@6ad59de70ee7e9c0a11c665c4439b5c148c74328 # v2.0.1
        with:
          action: set-drift-env
          issue: ${{toJSON(matrix.issue)}}

      - uses: suzuki-shunsuke/tfaction@6ad59de70ee7e9c0a11c665c4439b5c148c74328 # v2.0.1
        with:
          action: setup

      - name: terraform init
        uses: suzuki-shunsuke/tfaction@6ad59de70ee7e9c0a11c665c4439b5c148c74328 # v2.0.1
        with:
          action: terraform-init

      - uses: suzuki-shunsuke/tfaction@6ad59de70ee7e9c0a11c665c4439b5c148c74328 # v2.0.1
        with:
          action: test

      - uses: suzuki-shunsuke/tfaction@6ad59de70ee7e9c0a11c665c4439b5c148c74328 # v2.0.1
        with:
          action: plan

      - uses: suzuki-shunsuke/tfaction@6ad59de70ee7e9c0a11c665c4439b5c148c74328 # v2.0.1
        if: always()
        with:
          action: update-drift-issue
          status: ${{job.status}}
